### ISSUE TITLE
Some Models are exploded on Import

### ISSUE THREAD

**Issue by AnecAllods** [paulus-allods/blender-import#2] opened 2023-10-28 19:51 UTC
First of all, thank you for this addon, You have made multiple creative ideas Allods related I had possible. 

Onto the issue, it is shared with the old version as well multiple models, specifically the bigger models I noticed are always exploded.
examples:

\Server\game\data\World\Dungeons\Purgatory\Models\Purgatory.(Geometry).xdb
![image](https://github.com/paulus-allods/blender-import/assets/43345411/3ffc07a3-2c7b-4583-a1a2-4180eac32bad)

\Server\game\data\World\Dungeons\InstHadagan1\Hadagan_Instance_01.(Geometry).xdb
![image](https://github.com/paulus-allods/blender-import/assets/43345411/1b3f736c-d08f-43ea-bef4-12c3a34345b0)

**Comment by paulus-allods** [comment] 2023-10-29 21:46
Hi @AnecAllods, thanks for reporting the issue !

There was indeed an issue with the vertex index on these models. The `vertexBufferOffset` was ignored and therefore models were not properly built.

The issue is fixed on [0.0.3](https://github.com/paulus-allods/blender-import/releases/tag/0.0.3): 

![image](https://github.com/paulus-allods/blender-import/assets/40248377/164dae7b-5c70-44fe-94e6-25bb9fd75e1d)

I think I should reconsider refactoring this part of the code, it has been a long time since I wrote it and I realize I don't remember why I overcomplicated the code on vertex indexes parts 😄.

**Closed as completed by paulus-allods** 2023-10-29 21:46 UTC
